version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/plugin-transform-destructuring"
    versions:
    - 7.12.1
    - 7.13.0
  - dependency-name: "@babel/parser"
    versions:
    - 7.12.11
    - 7.12.16
    - 7.13.12
    - 7.13.4
  - dependency-name: danger
    versions:
    - 10.6.0
    - 10.6.2
    - 10.6.3
  - dependency-name: web-ext
    versions:
    - 5.5.0
  - dependency-name: ws
    versions:
    - 7.4.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
